### ISSUE TITLE
Why is there a key for old-paste?

### ISSUE THREAD

**Issue by mark-hahn** [t9md/atom-clip-history#1]
I haven't tried using this package yet but in thinking it through is would seem to me that you only need the one normal paste key-binding.  Hitting it once would paste and the second and later presses would go back in the buffer.

If I'm right you might consider an option for this behavior.  It would be nice to have only one key (ctrl-V for me) to remember.  Also I have all variations of ctrl-V already assigned.

**Comment by t9md** [comment]
I just followed my finger muscle memory.
I understand your point, yes its better if user can do with one-key(or command).
I will try your approach.

Thanks for good suggestion.

**Comment by mark-hahn** [comment]
Thanks for listening.

>  yes its better if user can do with one-key

I'm not sure it is better.  I just thought I'd like to try it that way.
Make it an option.

**Comment by t9md** [comment]
> I'm not sure it is better.  I just thought I'd like to try it that way.
> Make it an option.

I didn't make it an option.
After I implemented and tested behavior, its better (as my opinion) than before.
Of course its a bit different for user from Emacs, Bash, Zsh like me but I like this one-key pop up behavior  .
So this is design choice. I chose one-key pop up approach you suggested.

Anyway thanks for Idea.
