### ISSUE TITLE
Re-copying text does not make it the most recent paste item.

### ISSUE THREAD

**Issue by filipesilva** [t9md/atom-clip-history#2]
Title is a bit confusing, but I did not know how to phrase it better. Imagine I have the following:

```
one
two
```

I copy `one`, then copy `two`, then copy `one` again. If I paste, I'll get `two` whereas I would expect to get `one` since that was the last thing I copied.

This problem gets compounded as time goes by, since it is likely I try to copy pase a certain string twice during a coding session.

**Comment by t9md** [comment]
Sorry for this inconvenience, I can fix soon. wait for a second.

**Comment by filipesilva** [comment]
Don't apologize man, you're doing me a favor by making this plugin :D

**Comment by t9md** [comment]
Yes, I know ;).
Released new version, try again.
Thanks for catching this.

**Comment by filipesilva** [comment]
Looks good, thanks!

**Comment by t9md** [comment]
You're welcome!
