### ISSUE TITLE
Doesn't seem to work with vim-mode-plus

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-clip-history#4]
I got directed to this repo from vim-mode-plus and thought this'd integrate with it. Maybe I'm wrong?

**Comment by t9md** [comment]
No integration, this is completely independent package from vim-mode-plus.
I use this package in vim-mode-plus's insert-mode to pop old clip history by setting following keymap.

```
'atom-text-editor.vim-mode-plus.insert-mode':
  'ctrl-y': 'clip-history:paste'
  'cmd-y': 'clip-history:paste-newer'
  'ctrl-Y': 'clip-history:paste-last'
```

**Comment by chenglou** [comment]
The pasting's fine, but vim's yanking isn't registered as a copy

**Comment by t9md** [comment]
Here is my vim-mode-plus's setting.
Its saved as `config.cson` you can open it from atom's menu.
But normally you can reach setting view from each package's setting button(so not recommend direct editing unless you understand).

So, the setting you have to enable is `useClipboardAsDefaultRegister` I believe.

```
  "vim-mode-plus":
    useClipboardAsDefaultRegister: true
    useSmartcaseForSearch: true
    incrementalSearch: true
    stayOnTransformString: true
    flashOnUndoRedo: true
    setCursorToStartOfChangeOnUndoRedo: true
    stayOnYank: true
    flashOnUndoRedoDuration: 150
    showHoverSearchCounter: true
    showHoverOnOperate: true
```

**Comment by chenglou** [comment]
Ah I see, thanks again!

**Comment by t9md** [comment]
Solved?

**Comment by chenglou** [comment]
Yes =)

**Comment by t9md** [comment]
Good!
