### ISSUE TITLE
Possible to use with vim-mode-plus but without "Use Clipboard as default register"

### ISSUE THREAD

**Issue by axelson** [t9md/atom-clip-history#7]
I'd like to be able to use this with vim mode plus but I don't like the "use clipboard as default register" because it clutters up my clipboard history. Is there a way to use this plugin without the "Use Clipboard as default register" option?

**Comment by t9md** [comment]
Not sure your question. Just disabling "Use Clipboard as default register" is not enough?
It is disabled(=false) by default btw.

**Comment by t9md** [comment]
I think I understand your point.
Short answer is No.
So what you want is with "UseClipboardAsDefaulRegister" off, but want to still use clip board history provided this package right?
This package maintains history by spying `atom.clipboard.write` call.

**Comment by axelson** [comment]
Okay, thanks. Can we at least get that requirement added to the README of this project?

**Comment by t9md** [comment]
I don't think putting requirement is necessary and rather confusing.
If you disabled "UseClipboardAsDefaulRegister" in vmp, vmp manage clipboard independently, so this is out of scope of this clip-history package.

Putting "when you don't use Atom's clipbord then this plugin don't work" is a bit strange.

If I have time, ideal solution is to add special integration support for vmp which spy `y`, `Y`, `c` etc commands to maintain history.

**Comment by axelson** [comment]
> If I have time, ideal solution is to add special integration support for vmp which spy y, Y, c etc commands to maintain history.

Yes! That would be fantastic 👍
